### ISSUE TITLE
Incorrect Output File

### ISSUE THREAD

**Issue by yadeleke** [alsterman/wellness2tcx#3]
Thanks so much for creating this. 

I tried uploading the output file to Strava and my 5km run on the treadmill is showing up on Strava as 1,500km. It also has some information about Wattage.

Any ideas about what's wrong?

**Comment by alsterman** [comment]
Hey, the program is designed for cycling. This is as I used to exercise on MyWellness bikes.
If you send your input file, I could have a look at it (no promises).
