### ISSUE TITLE
Corrupt_method

### ISSUE THREAD

**Issue by Jstoqui** [alsterman/wellness2tcx#4]
First of all, thank you very much for the initiative, could you leave the original "Hdistance" data and remove "add-distance-calculated"?

I think that only the change in line 27 of the core.cljc file would be necessary.

I have no experience with CLOJURE.

I'd appreciate your help.

**Comment by alsterman** [comment]
Hi, the problem I found is that the Hdistance raw data was highly rounded off. This made strava angry as it ignores the speed field and calculates speed from the distance.
